server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog
  data:
    mongodb:
      username: usr-mongo
      password: pwd-mongo
      database: dev-mongo
      port: 27017
      host: localhost

feign:
  circuitbreaker:
    enabled: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        allow-health-indicator-to-fail: false
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 3s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      serie-service:
        base-config: default