server:
  port: 8079

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: api-catalog
          uri: lb://api-catalog
          predicates:
            - Path=/api/v1/catalog/**
        - id: api-serie
          uri: lb://api-serie
          predicates:
            - Path=/api/v1/series/**
        - id: api-movie
          uri: lb://api-movie
          predicates:
            - Path=/api/v1/movies/**

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
